--IMPORTED  Sales_data_sample

-- EVALUATING IMPORTED DATA
SELECT * FROM sales_data_sample 

--INSPECTING DATA 
SELECT DISTINCT STATUS FROM sales_data_sample 
SELECT DISTINCT PRODUCTLINE FROM sales_data_sample
SELECT DISTINCT YEAR_ID FROM sales_data_sample 
SELECT DISTINCT CITY FROM sales_data_sample 
SELECT DISTINCT COUNTRY FROM sales_data_sample 
SELECT DISTINCT TERRITORY FROM sales_data_sample 

-- TO EVALUATE EACH NUMBER OF MONTH IN EACH YEAR 
SELECT DISTINCT MONTH_ID FROM sales_data_sample 
 WHERE year_id = 2005

QUESTION ONE
-- WHICH MONTH HAD THE HIGHEST SALES ?

-- ANSWER - The month of NOVEMBER recorded the highest revenue 

	SELECT month_id, ROUND(SUM(Sales),2) REVENUE
	FROM sales_data_sample
	GROUP BY month_id
	ORDER BY REVENUE DESC;
	
QUESTION TWO 
-- WHICH CITY SOLD THE MOST PRODUCT

--ANSWER - Madrid recorded the highest revenue 


	SELECT CITY, ROUND(SUM(Sales),2) REVENUE
		FROM sales_data_sample
		GROUP BY CITY
		ORDER BY REVENUE DESC;

QUESTION 3
-- WHICH PRODUCT ARE OFTEN SOLD TOGETHER 

-- ANSWER VINTAGE CARS ARE OFTEN SOLD TOGETHER 

SELECT * FROM sales_data_sample WHERE ORDERNUMBER = 10411
-- INDEX (15 & 16) & (11 & 12) 

	SELECT  DISTINCT ORDERNUMBER ,STUFF(	
		(SELECT ',' + PRODUCTCODE
		FROM sales_data_sample P
		WHERE ORDERNUMBER IN(
			SELECT ORDERNUMBER FROM (
				SELECT ORDERNUMBER , COUNT(*) SN
					FROM sales_data_sample
					WHERE STATUS = 'Shipped'
					GROUP BY ORDERNUMBER
					)M
					WHERE SN =2
					)
					AND P.ORDERNUMBER = S.ORDERNUMBER
					FOR XML PATH('')),1,1,'') PRODUCTCODES
	 FROM sales_data_sample S
	 ORDER BY 2 DESC


 QUESTION 4
 -- WHICH DAY OF THE WEEK HAS THE HIGHEST ORDER ?

 --ANSWER - The 6th day of the week recorded the highest order 
 
	SELECT SUM(SALES) FROM sales_data_sample;

	SELECT DATEPART(dw,ORDERDATE) WEEKDAY , SUM(QUANTITYORDERED) AS ORDERS
		FROM sales_data_sample 
		GROUP BY DATEPART(dw,ORDERDATE) 
		ORDER BY ORDERS DESC

-- WHICH DAY OF THE WEEK HAS THE HIGHEST SALES 

	SELECT DATEPART(dw,ORDERDATE) WEEKDAY , ROUND(SUM(SALES),2) AS REVENUE 
		FROM sales_data_sample 
		GROUP BY DATEPART(dw,ORDERDATE) 
		ORDER BY REVENUE DESC

QUESTION 5 
	--WHAT IS THE AVERAGE ORDER VALUE 

	--ANSWER - The average order is 35


	SELECT AVG(QUANTITYORDERED) AVERARE_ORDER
		FROM sales_data_sample 


QUESTION 6 
	---WHAT ARE THE TOP 5 BEST SELLING PRODUCTS 

	-- ANSWER - The top 5 selling products include Classic Cars,Vintage Cars,Motocycles,Truck and Buses and Planes 


	SELECT TOP 5 PRODUCTLINE , ROUND(SUM(SALES),2) REVENUE
		FROM sales_data_sample 
		GROUP BY PRODUCTLINE
		ORDER BY REVENUE DESC ;

QUESTION 7
	-- WHAT TIME SHOULD WE DISPLAY ADVERTISMENT FOR MAXIMISE CUSTOMER ENGAGEMENT ?

	--ANSWER - The 3rd quarter of the year requires maximum customer engagement 

	--ANSWER - THE 6th and 7th month also requires maximum customer engagement 


	SELECT QTR_ID , ROUND(SUM(SALES),2) REVENUE 
		FROM sales_data_sample 
		GROUP BY QTR_ID
		ORDER BY 2 DESC;

	SELECT MONTH_ID , ROUND(SUM(SALES),2) REVENUE 
		FROM sales_data_sample 
		GROUP BY MONTH_ID
		ORDER BY REVENUE DESC;



QUESTION 8
-- WHICH DEAL SIZE HAS THE HIGHEST SALES 

-- ANSWER - The highest revenue for deal size was the medium 


	SELECT dealsize, ROUND(sum(sales),2) Revenue 
		FROM sales_data_sample 
		GROUP BY dealsize
		ORDER BY 2 desc

QUESTION 9
--wHAT WAS THE BEST MONTH FOR EACH YEAR AND THE REVENUE PER MONTH 

-- FOR YEAR 2003 

--ANSWER - November was the best month for the year 2003

	 SELECT MONTH_ID, ROUND(SUM(SALES),2) REVENUE, COUNT(ORDERLINENUMBER) AS FREQUENCY 
		FROM sales_data_sample 
		WHERE YEAR_ID = 2003 
		GROUP BY MONTH_ID
		ORDER BY 2 DESC ;

-- FOR YEAR 2004

--ANSWER - November was the best month for the year 2004


	SELECT MONTH_ID, ROUND(SUM(SALES),2) REVENUE, COUNT(ORDERLINENUMBER) AS FREQUENCY 
		FROM sales_data_sample 
		WHERE YEAR_ID = 2004
		GROUP BY MONTH_ID
		ORDER BY 2 DESC ;

-- FOR YEAR 2005 

--ANSWER - May was the best month for the year 2005 (May was the last month for 2005)

	SELECT MONTH_ID, ROUND(SUM(SALES),2) REVENUE, COUNT(ORDERLINENUMBER) AS FREQUENCY 
		FROM sales_data_sample 
		WHERE YEAR_ID = 2005
		GROUP BY MONTH_ID
		ORDER BY 2 DESC ;

QUESTION 10

--NOVEMBER BEIGN THE BEST MONTH, LET'S EVALUATE PRODUCT SOLD IN NOVEMBER 

-- ANSWER - Classic Cars are was the most purchased product for the month of November in the year 2003 and 2004

-- FOR 2003 

	SELECT MONTH_ID,PRODUCTLINE, ROUND(SUM(SALES),2) REVENUE, COUNT(ORDERLINENUMBER) AS FREQUENCY 
		FROM sales_data_sample 
		WHERE YEAR_ID = 2003 AND MONTH_ID = 11
		GROUP BY MONTH_ID,PRODUCTLINE
		ORDER BY REVENUE DESC ;
	
	-- FOR 2004 


	SELECT MONTH_ID,PRODUCTLINE, ROUND(SUM(SALES),2) REVENUE, COUNT(ORDERLINENUMBER) AS FREQUENCY 
		FROM sales_data_sample 
		WHERE YEAR_ID = 2003 AND MONTH_ID = 11
		GROUP BY MONTH_ID,PRODUCTLINE
		ORDER BY REVENUE DESC ;

	
QUESTION 11 

-- THE BEST CUSTOMERS  

	
	SELECT CUSTOMERNAME, 
		ROUND(SUM(SALES), 2) REVENUE ,
		COUNT(ORDERLINENUMBER) FREQUENCY, 
		MAX(ORDERDATE) LAST_PURCHASE_DATE,
		(SELECT MAX(ORDERDATE) FROM sales_data_sample) MAX_ORDERDATE,
		DATEDIFF(DD,MAX(ORDERDATE),(SELECT MAX(ORDERDATE) FROM sales_data_sample)) RECENCY
	FROM sales_data_sample
	GROUP BY CUSTOMERNAME